### ISSUE TITLE
Inline rows alternate colors for better visibility

### ISSUE THREAD

**Issue by fabiocaccamo** [elky/django-flat-theme#10]

**Comment by elky** [comment]
Can you attach screenshot of problem section, please? Thanks

**Comment by fabiocaccamo** [comment]
This is not a problem, it's just a suggestion to improve inline rows style.

For example in inlines list even rows could have a background color: #FFFFFF and odd rows a background color: #F5F5F5

**Comment by elky** [comment]
Implemented in 0.9.5: https://github.com/elky/django-flat-theme/blob/b329d69960e3b554f998004a26759edf78c26198/flat/static/admin/css/base.css#L306
