### ISSUE TITLE
Wrong field style caused by its name

### ISSUE THREAD

**Issue by fabiocaccamo** [elky/django-flat-theme#12]
I had a situation where 2 fields were on the same row, I checked the css and I saw that one of them had a class called field-box just because the field name was box, so I solved it reming the field, but it would be better to use a different naming convention to prevent that this could happen.

**Comment by elky** [comment]
Well this theme is just CSS skin for default django admin.

So please report this issue to django bug tracker - https://docs.djangoproject.com/en/1.8/internals/contributing/bugs-and-features/#reporting-bugs

Thanks!
