### ISSUE TITLE
filter_horizontal filter css problem

### ISSUE THREAD

**Issue by fabiocaccamo** [elky/django-flat-theme#13]
![schermata 2015-05-28 alle 12 48 43](https://cloud.githubusercontent.com/assets/1035294/7858379/00cd9a6e-0538-11e5-85cf-fedeb8ef112c.png)

**Comment by elky** [comment]
Thanks for reporting, I'll check it out.

**Comment by roebuk** [comment]
Which browser(s) are currently being affected by this issue?

**Comment by fabiocaccamo** [comment]
I noticed it using Chrome 41

**Comment by roebuk** [comment]
I cannot replicate this, sorry.

**Comment by drjackild** [comment]
Same thing, I using Firefox and also check it in Safari. Everything is OK.

**Comment by elky** [comment]
I'll reopen this ticket if someone else report same issue.
