### ISSUE TITLE
The edit and add icons are too close together on the change page

### ISSUE THREAD

**Issue by jarshwah** [elky/django-flat-theme#19]
I think the icons on the change page for add/edit are either too small, or too close together. I've attached a screenshot to demonstrate.

<img width="344" alt="flat-admin-icons" src="https://cloud.githubusercontent.com/assets/541083/8537041/8f12a930-249c-11e5-97b8-72b016552787.png">

I added a `margin-left: 5px` to the `.form-row img` selector, and it looks more reasonable - though the icons still look too small:

<img width="336" alt="flat-admin-icons-margin" src="https://cloud.githubusercontent.com/assets/541083/8537084/197d737a-249d-11e5-8a57-a0b15c22a46d.png">

I'm not sure how much scope you have to effect this kind of change since you're aiming for backwards compatibility with the existing admin.

**Comment by elky** [comment]
Done. Will be available in next release soon.
Thanks for reporting!
