### ISSUE TITLE
Change icons to something modern

### ISSUE THREAD

**Issue by drjackild** [elky/django-flat-theme#20]
Have a desire to replace the current icons in the interface (with something like Font Awesome). But I see that there is an additional branch with the same purpose. There is a sense in completion, or the author has completed and will soon be merging?

**Comment by collinanderson** [comment]
see also https://code.djangoproject.com/ticket/20597

**Comment by elky** [comment]
@DrJackilD @collinanderson can you guys help me to test new icons, please?

I pushed new branch called `flat-icons` so you can run:
 `pip install git+https://github.com/elky/django-flat-theme.git@flat-icons --upgrade`
in your test project to see how it works now.

P.S. Code will be refactored a bit later so just check how it works visually.

Thank you.

**Comment by drjackild** [comment]
Sure, will test it today in evening.

**Comment by drjackild** [comment]
@elky OK, I was tested it and find problem. FontAwesome doesn't link to admin's page, because there is wrong path. I was tried to change it, but have no effect (it's probably because I tested it on ready-to-production project, and make `manage.py collectstatic` before)
![screenshot - 30 07 2015 - 04 35 38](https://cloud.githubusercontent.com/assets/1544738/8973977/cd0defc6-3674-11e5-9ada-1a1354b42fe6.png)
![screenshot - 30 07 2015 - 04 37 43](https://cloud.githubusercontent.com/assets/1544738/8974046/c5cf0adc-3675-11e5-8ece-d941d7f4ce6a.png)

UPD. Yeah, I'm edited FontAwesome path in font-awesome.css in django-flat-theme folder and all working well now. And that's looking really awesome with FontAwesome :) Great job, man!

**Comment by elky** [comment]
> I'm edited FontAwesome path in font-awesome.css

Oh, I completely forgot that file names are case sensitive in unix. Thanks!

**Comment by timgraham** [comment]
What's your assessment of the "Icon Font" vs. "Inline SVG" [article](https://css-tricks.com/icon-fonts-vs-svg/) that Collin linked to on the Django ticket?

**Comment by elky** [comment]
@timgraham replied there.

**Comment by elky** [comment]
1.1.0 version is shipped with flat svg icons.
