### ISSUE TITLE
Mobile responsive?

### ISSUE THREAD

**Issue by billmei** [elky/django-flat-theme#21]
This is really awesome! The flat design made me think the CSS made everything mobile-responsive out of the box, but it turns out that's still yet to be implemented :confused: Is responsiveness on the roadmap?

**Comment by elky** [comment]
Yeah, I was thinking about responsive but there are few difficulties: we cannot control third-party apps which have their own layout, and also I have no idea what to do with WYSIWYG editors on mobile devices (this is big UX question). So I don't think we will see fully responsive theme in near future - we need to discuss it with the community.

**Comment by ssbb** [comment]
I think we can work only on built-it admin responsiveness and don't care about 3rd party apps. No one will adapt their apps for responsive layout when django admin is not reponsive at all.

**Comment by ssbb** [comment]
Anyway I think that responsive for built-in features (lists, forms) with some minor problems for 3rd party apps (at first time only I hope) is much better than non-responsive admin at all.

**Comment by elky** [comment]
FYI I'm working on it, will be available in feature branch soon.

**Comment by billmei** [comment]
@elky Sweet, thanks for responding to this! :+1: Would help tremendously for accessing admin settings on-the-go.

**Comment by ssbb** [comment]
@elky good news, thanks! :+1:

**Comment by elky** [comment]
**Got first results** :metal:

<img width="320" src="https://cloud.githubusercontent.com/assets/209663/11604237/c7fa7f30-9b0b-11e5-9e9e-169bb87d9bca.PNG"> <img width="320" src="https://cloud.githubusercontent.com/assets/209663/11604238/cbe31120-9b0b-11e5-86ce-e9b72e7d8e6d.PNG">

**Comment by ssbb** [comment]
@elky looks cool :)

I think proposal - maybe decrease left/right padding on main content area (apps, recent actions) for extra small devices? Maybe remove it all since this blocks have internal paddings already?

**Comment by dave4jr** [comment]
Hi Elky, thanks for all your work on this. Any update on the responsive side of this?

**Comment by elky** [comment]
BOOM 💣 

https://github.com/elky/django-flat-responsive

**Comment by billmei** [comment]
@elky Awesome work! :clap:
