### ISSUE TITLE
django-admin-tools menu compatibility?

### ISSUE THREAD

**Issue by hughstimson** [elky/django-flat-theme#22]
It would be great if this theme could (eventually) be compatible with the drop-down menus provided by django-admin-tools.

I understand you can't support compatibility with every other admin modification plugin, but my impression is that django-admin-tools in particular is mature and widely used.

https://pypi.python.org/pypi/django-admin-tools

Thanks for a great package.

**Comment by elky** [comment]
django-flat-theme is [officially](https://github.com/django/django/commit/35901e64b043733acd1687734274553cf994511b) going to be part of Django 1.9 so django-admin-tools will has to update their design :) When they do this - I'll snatch CSS code to this theme to make it compatible with old Django versions.

Thanks, @hughstimson

**Comment by elky** [comment]
Oops, accidentally closed it.

**Comment by hughstimson** [comment]
Oh that's good news. Thanks.

**Comment by elky** [comment]
@hughstimson guys from **django-admin-tools** have updated styles for new django theme so last version works fine with **django-flat-theme** according to my quick review. Can you confirm it?
