### ISSUE TITLE
Easy way to remove Roboto font on app level?

### ISSUE THREAD

**Issue by nmtitov** [elky/django-flat-theme#23]
Hi, is there an easy way to remove Roboto font on app level?

**Comment by elky** [comment]
@nmtitov I think the easiest way is this:

Just create copy of `base.css` in your `<app>/static/admin/css/base.css`, find all "Roboto" mentions and replace with what you need. One only thing is that you need to put your app before `'flat'` in INSTALLED_APPS section.

**Comment by nmtitov** [comment]
Thank you
