### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by Cykooz** [elky/django-flat-theme#24]
Please, do not use in the _MANIFEST.in_ instructions that's like this:

```
recursive-include flat *
```

In this case, all files will be included into the package distribution. For example, such as the files: *.pyc, .DS_Store. Because of this, when I installed this package with the following command:

```
easy_install django-flat-theme
```

I got an error:

```
Traceback (most recent call last):
...
  File "/home/.../setuptools-18.2-py3.4.egg/setuptools/command/bdist_egg.py", 
line 391, in scan_module
ValueError: bad marshal data (unknown type code)
```

It is best to explicitly specify the file extensions to be included in the distribution. For example:

```
recursive-include flat *.py *.html *.css *.js
```

**Comment by elky** [comment]
@Cykooz Just updated package to 1.1.1. Can you test it now, please?

**Comment by Cykooz** [comment]
Thank you, it works now.
