### ISSUE TITLE
Declare that django-flat-theme supports Python 3

### ISSUE THREAD

**Issue by aaugustin** [elky/django-flat-theme#27]
caniusepython3.com reports it as unsupported, while it obviously works. It would be nice to add the trove classifiers to setup.py. See https://github.com/brettcannon/caniusepython3#how-do-you-tell-if-a-project-has-been-ported-to-python-3 for details or just steal it from Django.

**Comment by elky** [comment]
Done!

[![](https://caniusepython3.com/project/django-flat-theme.png)](https://caniusepython3.com/project/django-flat-theme)

Thanks for suggestion @aaugustin

**Comment by aaugustin** [comment]
Great, thanks!
