### ISSUE TITLE
DateTimeField in admin TabularInline has unsightly left margin

### ISSUE THREAD

**Issue by timgraham** [elky/django-flat-theme#28]
![25827](https://cloud.githubusercontent.com/assets/411869/11451874/b7a382c6-95a2-11e5-9a44-c64bf1c67fe2.png)

from https://code.djangoproject.com/ticket/25827

**Comment by elky** [comment]
Thanks @timgraham 
I fixed it here https://github.com/elky/django-flat-theme/commit/f281e25e94a97be3468c1e898fea32d4ab0fdb7a but this fix is differ from that I made in Django PR so if you want to test it please use https://github.com/django/django/pull/5743
