### ISSUE TITLE
Admin's "no" icon is incorrect and should be replaced

### ISSUE THREAD

**Issue by evildmp** [elky/django-flat-theme#3]
See https://code.djangoproject.com/ticket/24491 for rationale.

django-flat-theme might be a good opportunity to fix this issue too.

**Comment by roebuk** [comment]
https://github.com/elky/django-flat-theme/pull/14

**Comment by elky** [comment]
Solved here https://github.com/django/django/pull/5186. Will be shipped in the app soon.
