### ISSUE TITLE
Not working at production stage

### ISSUE THREAD

**Issue by ghost** [elky/django-flat-theme#31]
Hi, for some reason django-flat-theme it is not working at production stage, it is strange because "flat" it is setted in base.py before django.contrib.admin, and the same file it is used by production and dev. Any ideas ??? Thanks a lot !

**Comment by elky** [comment]
Did you run `manage.py collectstatic`?

**Comment by ghost** [comment]
Crap, i forget it ! Thank you ! I am new at Django.
