### ISSUE TITLE
Textareas cannot be resized horizontally

### ISSUE THREAD

**Issue by aaugustin** [elky/django-flat-theme#4]
The CSS contains:

```
textarea {
    resize: vertical;
}
```

Sometimes you want more horizontal space.

Why take control from the user? ;-)

**Comment by elky** [comment]
> Why take control from the user?

Agree. I personally prefer to disable horizontal resize because sometimes it breaks layout. But it seems safe in Django admin.

**Comment by aaugustin** [comment]
I understand.

Speaking for myself, I don't care about "breaking" the layout if that helps me to type or read text comfortably.

Thanks for the fix!
