### ISSUE TITLE
Action select box height is to small

### ISSUE THREAD

**Issue by raphaelm** [elky/django-flat-theme#6]
The current select box that is displayed above a list for selecting an action is to small to display the text properly.

Screenshot with german locale: 
![Screen](https://drop.rami.io/I4i3Bl/)

**Comment by elky** [comment]
@raphaelm can you provide browser and OS info please? Thanks

**Comment by raphaelm** [comment]
Sure, it's Google Chrome on Arch Linux. If there is anything I can do to help debugging, I'd be happy to do so :)

:+1: for the great theme! :)

**Comment by elky** [comment]
Fixed in [0.9.2](https://pypi.python.org/pypi/django-flat-theme/0.9.2).

> If there is anything I can do to help debugging, I'd be happy to do so :)

It would be great if you just continue to use this app - it's the best debugging :)
