### ISSUE TITLE
Layout problem on multiple element by line admin rendering

### ISSUE THREAD

**Issue by Christophe31** [elky/django-flat-theme#7]
Hi,

I'm having (with my French up to date Firefox Linux & Windows) issues on rendering.

I may be cause of the problem as I added chosen widget…

[edit] I am the cause of the problem, my widget need to disable overflow hidden in form row and it does it automatically… and if I use !important to overflow hidden, my widget don't work properly as it can't pop from the line…

I agree it's not really your issue but I don't really know how to handle my MixIn which works pretty well in classic admin.

![screen_flat_bug](https://cloud.githubusercontent.com/assets/84683/7050189/da34b480-de1f-11e4-8eb1-1393227e1c2c.png)

Do you think of a work around for advanced admin user injecting widget relying on classic overflowing style?

**Comment by elky** [comment]
@Christophe31  I think clearfix would be a solution to fix it.
Can you attach screenshot of this section in classic admin view, please?

**Comment by Christophe31** [comment]
Haha, sorry, you got me, I tryed this widget in admin but apparently not in a mutiple widget per line context… my bad.

But you are right, even if horizontal lines still go anywhere, clear:all; fix most of the issue.

Thanx a lot for your quick answer…
