### ISSUE TITLE
Custom colors and logo

### ISSUE THREAD

**Issue by fabiocaccamo** [elky/django-flat-theme#9]
Hi, thanks for this theme, I think it is one of the best and modern Django admin themes available.

Generally for each client I add a custom logo and I set 2 custom colors, a light and a dark one.

It would very nice having the possibility to customize these 3 things using settings.py or by providing an  small admin panel for the theme. 

What do you think about it?

**Comment by elky** [comment]
Well I think it's great. I currently have the same task for one of my clients but this feature seems not easy to realize. As a perfect solution I would like to render color variables to the separate css file but after that we have to make `collectstatic` command when you click 'Save' in admin (or when you change var in settings.py). So this feature requires quite good python background.

**Comment by fabiocaccamo** [comment]
Could you just create the separate css file with color variables and logo url?
After that I will do the python to edit the css variables from the admin interface.

**Comment by edvm** [comment]
+1 to this request ^^

**Comment by fabiocaccamo** [comment]
I did it, check it: https://github.com/fabiocaccamo/django-admin-interface

**Comment by edvm** [comment]
@fabiocaccamo great! could you please push a pull request to tihs repo? :) (my apologies if you already did it :)

**Comment by fabiocaccamo** [comment]
Thanks! 
I'm sorry but it's not possible because **django-admin-interface** is not a fork of **django-flat-theme**.
I used django-flat-theme as 'base-theme' and it is installed as a dependency lib, in this way in a future it will be possible to switch between base-themes if needed.

**Comment by elky** [comment]
This is awesome, thanks @fabiocaccamo!
